# Generated by Django 5.2 on 2025-04-18 19:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='try_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challengehistory',
            name='challenge_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
